pipeline:
    restore-cache:
        image: drillster/drone-volume-cache
        restore: true
        mount:
            - /home/rust/.cargo/git
            - /home/rust/.cargo/registry
            - ./target
        volumes:
            - /tmp/cache:/cache

    build:
        image: ekidd/rust-musl-builder:stable
        commands:
            - make release
            - make optimize

    build-image:
        image: plugins/docker
        settings:
            repo: static-web-server
            tags: latest
            auto_tag: true
            dockerfile: ./docker/Dockerfile
            registry: registry.joseluisq.net

    rebuild-cache:
        image: drillster/drone-volume-cache
        rebuild: true
        mount:
            - /home/rust/.cargo/git
            - /home/rust/.cargo/registry
            - ./target
        volumes:
            - /tmp/cache:/cache
        when:
            branch: develop

image_pull_secrets:
    - dockerconfig
