kind: pipeline
name: default

steps:
  - name: build
    image: ekidd/rust-musl-builder:stable
    commands:
      - sudo chown -R rust:rust $(pwd)
      - cargo build --release
      - BINARY_PATH="./bin/$(cat Cargo.toml | sed -n 's/name = "\([^}]*\)"/\1/p')""
      - echo "Size before:"
      - du -sh $BINARY_PATH
      - strip $BINARY_PATH
      - echo "Size after:"
      - du -sh $BINARY_PATH
