kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.joseluisq.net

  - name: build
    image: registry.joseluisq.net/rustatic:latest
    commands:
      - cargo --version
      - rustc --version
      - rustup --version
