---
kind: pipeline
type: docker
name: development

platform:
  os: linux
  arch: amd64

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
    - name: cargo-cache
      path: /home/rust/.cargo
  settings:
    restore: true
    mount:
      - /home/rust/.cargo/git
      - /home/rust/.cargo/registry
      - ./target

- name: test
  image: joseluisq/rust-linux-darwin-builder:1.41.1
  commands:
    - make test

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
    - name: cargo-cache
      path: /home/rust/.cargo
  settings:
    rebuild: true
    mount:
      - /home/rust/.cargo/git
      - /home/rust/.cargo/registry
      - ./target

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: cargo-cache
    host:
      path: /tmp/cargo-cache

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
    - develop
    - feature/*
    - bugfix/*
    - hotfix/*


---
kind: pipeline
type: docker
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: release
  image: joseluisq/rust-linux-darwin-builder:1.41.1
  commands:
    - make test


---
kind: pipeline
type: docker
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci-cd

depends_on:
- development

trigger:
  status:
  - success
  - failure
