pipeline:
    restore-cache:
        image: drillster/drone-volume-cache
        restore: true
        mount:
            - /home/rust/.cargo/git
            - /home/rust/.cargo/registry
            - ./target
        volumes:
            - /tmp/cache:/cache

    build:
        image: ekidd/rust-musl-builder:stable
        commands:
            - make release
            - make optimize

    build-image:
        image: plugins/docker
        dockerfile: ./docker/Dockerfile
        registry: registry.joseluisq.net
        repo: registry.joseluisq.net/static-web-server
        tags: latest
        tags: [ latest, '${DRONE_TAG}' ]
        when:
            event: tag

    rebuild-cache:
        image: drillster/drone-volume-cache
        rebuild: true
        mount:
            - /home/rust/.cargo/git
            - /home/rust/.cargo/registry
            - ./target
        volumes:
            - /tmp/cache:/cache
        when:
            branch: develop

image_pull_secrets:
    - dockerconfig
