kind: pipeline
name: default

steps:
  - name: test
    image: registry.joseluisq.net/rustatic:latest
    commands:
      - export PATH="$PATH:$HOME/.cargo/bin"
      - pwd -P
      - ls -lah
      - echo $PATH
      - cargo --version
      - rustc --version
      - rustup --version

image_pull_secrets:
  - dockerconfig
