pipeline:
    restore-cache:
        image: drillster/drone-volume-cache
        restore: true
        mount:
            - /home/rust/.cargo/git
            - /home/rust/.cargo/registry
            - ./target
        volumes:
            - /tmp/cache:/cache

    build-release:
        image: ekidd/rust-musl-builder:stable
        group: building
        commands:
            - make release
            - make optimize
            - make release-files

    publish-image:
        image: plugins/docker
        group: building
        registry: registry.joseluisq.net
        repo: registry.joseluisq.net/static-web-server
        dockerfile: ./docker/scratch/Dockerfile
        username:
            from_secret: registry_username
        password:
            from_secret: registry_password
        auto_tag: true
        when:
            event: tag

    publish-image-alpine:
        image: plugins/docker
        group: building
        registry: registry.joseluisq.net
        repo: registry.joseluisq.net/static-web-server
        dockerfile: ./docker/alpine/Dockerfile
        username:
            from_secret: registry_username
        password:
            from_secret: registry_password
        auto_tag: true
        auto_tag_suffix: alpine
        build_args:
            - SERVER_VERSION=${DRONE_TAG}-alpine
        when:
            event: tag

    publish-image-scratch-docker-hub:
        image: plugins/docker
        group: building
        repo: joseluisq/static-web-server
        dockerfile: ./docker/scratch/Dockerfile
        secrets: [dockerhub_username, dockerhub_password]
        auto_tag: true
        when:
            event: tag

    publish-image-alpine-docker-hub:
        image: plugins/docker
        group: building
        repo: joseluisq/static-web-server
        dockerfile: ./docker/alpine/Dockerfile
        secrets: [dockerhub_username, dockerhub_password]
        auto_tag: true
        auto_tag_suffix: alpine
        build_args:
            - SERVER_VERSION=${DRONE_TAG}-alpine
        when:
            event: tag

    publish-release:
        image: plugins/gitea-release
        group: building
        api_key:
            from_secret: gitea_token
        base_url: https://git.joseluisq.net/
        files:
            - ./bin/*.tar.gz
            - ./bin/*.zip
        prerelease: true
        checksum:
            - md5
            - sha1
        when:
            event: tag

    rebuild-cache:
        image: drillster/drone-volume-cache
        rebuild: true
        mount:
            - /home/rust/.cargo/git
            - /home/rust/.cargo/registry
            - ./target
        volumes:
            - /tmp/cache:/cache
        when:
            branch: develop
