kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.joseluisq.net
      repo: rustatic
      tags: latest

  - name: test
    commands:
      - rustup show

  - name: build
    commands:
      - rustatic $(pwd -P)
