status = [
    "test (pinned)",
    "test (stable)",
    "test (beta)",
    "test (linux-musl)",
    "test (linux-musl-arm64)",
    "test (linux-gnu)",
    "test (linux-gnu-arm64)",
    "test (linux-arm-gnueabihf)",
    "test (macos)",
    "test (macos-arm64)",
    "test (windows-msvc)",
    "test (windows-msvc-arm64)",
    "checks",
]
delete_merged_branches = true
timeout_sec = 1200 # 20 min
