[package]
name = "static-web-server"
version = "1.19.4"
authors = ["Jose Quintana <https://git.io/joseluisq>"]
license = "MIT OR Apache-2.0"
description = "A blazing fast static files-serving web server powered by Rust Iron."
repository = "https://github.com/joseluisq/static-web-server"
readme = "README.md"
keywords = [
    "docker-image",
    "static-web-server",
    "file-server",
    "http-server",
    "linux",
    "darwin",
    "musl-libc",
    "x86-64"
]
categories = ["network-programming", "web-programming::http-server"]
edition = "2018"
include = ["src/**/*", "Cargo.toml", "Cargo.lock"]

[[bin]]
name = "static-web-server"
path = "src/bin/server.rs"

[dependencies]
chrono = "0.4"
env_logger = { version = "0.8", default-features = false }
flate2 = "1.0"
humansize = "1.1"
hyper-native-tls = "0.3"
iron = "0.6"
iron-cors = "0.8"
log = "0.4"
mime = "0.2"
mime_guess = "1.8"
structopt = { version = "0.3", default-features = false }
time = "0.1"
url = "1.4"
percent-encoding = "2.1"
ctrlc = { version = "3.1", features = ["termination"] }

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.tikv-jemallocator]
version = "0.5"

[dev-dependencies]
openssl = { version = "0.10", features = ["vendored"] }
hyper = "0.10"
iron-test = "0.6"
tempfile = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
rpath = false
debug-assertions = false
