[package]
name = "rust-web-server"
version = "1.0.0"
authors = ["José Quintana <https://git.io/joseluisq>"]

[dependencies]
iron = ">= 0.5, < 0.7"
env_logger = "0.3.5"
playground-middleware = { git = "https://github.com/integer32llc/playground-middleware.git" }
envy = "0.3"
serde = "1.0"
serde_derive = "1.0"

[profile.release]
lto = true
