[package]
name = "static-web-server"
version = "0.0.0"
authors = ["Jose Quintana <https://git.io/joseluisq>"]
license = "MIT OR Apache-2.0"
description = "A blazing fast static files-serving web server powered by Rust Iron."
repository = "https://github.com/joseluisq/static-web-server"
readme = "README.md"
keywords = [
    "static-web-server",
    "file-server",
    "http-server",
    "linux",
    "darwin",
    "musl-libc",
    "x86-64",
    "docker-image"
]
categories = ["network-programming", "web-programming::http-server"]
edition = "2018"
include = ["src/**/*", "Cargo.toml", "Cargo.lock"]

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = { version = "0.2", features = ["compression"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
structopt = "0.3"
nix = "0.14"
signal = "0.7"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.3"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
