[package]
name = "static-web-server"
version = "1.0.0-beta.1"
authors = ["Jose Quintana <https://git.io/joseluisq>"]

[dependencies]
iron = "0.6"
log = "0.4"
chrono = "0.4"
env_logger = "0.7"
playground-middleware = { git = "https://github.com/joseluisq/iron-playground-middleware.git" }
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
flate2 = "1.0"

[profile.release]
lto = true
