[package]
name = "static-web-server"
version = "2.0.0-beta.1"
authors = ["Jose Quintana <https://git.io/joseluisq>"]
license = "MIT OR Apache-2.0"
description = "A blazing fast static files-serving web server."
repository = "https://github.com/joseluisq/static-web-server"
readme = "README.md"
keywords = [
    "static-web-server",
    "file-server",
    "http-server",
    "linux",
    "darwin",
    "musl-libc",
    "x86-64",
    "docker-image"
]
categories = ["network-programming", "web-programming::http-server"]
edition = "2018"
include = ["src/**/*", "Cargo.toml", "Cargo.lock"]

[[bin]]
name = "static-web-server"
path = "src/bin/server.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
warp = { git = "https://github.com/joseluisq/warp.git", branch = "0.3.x", features = ["tls","compression"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
structopt = "0.3"
nix = "0.14"
signal = "0.7"
num_cpus = { version = "1.13" }

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.3"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
