[package]
name = "static-web-server"
version = "1.0.0"
authors = ["Jose Quintana <https://git.io/joseluisq>"]
edition = "2018"

[dependencies]
iron = "0.6"
log = "0.4"
chrono = "0.4"
env_logger = "0.7"
structopt = "0.3"
flate2 = "1.0"
iron_staticfile_middleware = { git = "https://github.com/joseluisq/iron-staticfile-middleware.git" }

[profile.release]
lto = true
