[package]
name = "static-web-server"
version = "1.0.0-beta.3"
authors = ["Jose Quintana <https://git.io/joseluisq>"]

[dependencies]
iron = ">= 0.5, < 0.7"
log = "0.4"
chrono = "0.4"
env_logger = "0.5"
playground-middleware = { git = "https://github.com/integer32llc/playground-middleware.git" }
envy = "0.3"
serde = "1.0"
serde_derive = "1.0"
flate2 = "1.0"

[profile.release]
lto = true
