version: '3'

services:
  cs-server:
    image: cs-server-rust:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.5'
          memory: 50M
    ports:
      - "8015:8015"
    networks:
       - overlay

networks:
  overlay:
