# Project information
site_name: Static Web Server
site_description: 'A blazing fast and asynchronous web server for static files-serving ⚡'
site_author: 'Jose Quintana'
site_url: https://joseluisq.github.io/static-web-server/

# Repository
repo_name: joseluisq/static-web-server
repo_url: https://github.com/joseluisq/static-web-server/
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019-2021 Jose Quintana

# Theme
theme:
  name: 'material'
  logo: assets/rust_logo.svg
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Fira Sans'
    code: 'Droid Sans Mono'
  favicon: https://camo.githubusercontent.com/a08032a2db94aea229991af8f73c45cc95174c8066dc7a6b1f88a79c94cf1093/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f642f64352f527573745f70726f6772616d6d696e675f6c616e67756167655f626c61636b5f6c6f676f2e7376672f3130323470782d527573745f70726f6772616d6d696e675f6c616e67756167655f626c61636b5f6c6f676f2e7376672e706e67

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/joseluisq'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/joseluis_q'

markdown_extensions:
    - codehilite
    - admonition
    - meta
    - toc:
        permalink: true
    - markdown.extensions.tables
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.magiclink:
        repo_url_shortener: true
        repo_url_shorthand: true
        provider: "github"
        user: "facelessuser"
        repo: "pymdown-extensions"
    - pymdownx.tilde
    - pymdownx.emoji
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist
