[env]
E_ARGS = "--port=8787"
E_URL = "http://locahost"
SERVER_LOG_LEVEL = "trace"
SERVER_ROOT = "./public"
SERVER_ASSETS = "./public/assets"
SERVER_CORS_ALLOW_ORIGINS = "*"

[tasks.watch]
command = "cargo"
args = ["watch", "-cx", "run -- ${E_ARGS}"]

[tasks.run]
command = "cargo"
args = ["run", "--", "${E_ARGS}"]

[tasks.loadtest]
script = [
    "echo GET $E_URL | vegeta -cpus=12 attack -workers=10 -duration=60s -connections=10000 -rate=200 -http2=true | tee results.bin | vegeta report",
	"cat results.bin | vegeta report -reporter=plot > plot.html"
]
