[env]
PKG_PLATFORM = "x86_64-unknown-linux-musl"
PKG_NAME = { script = ["cat Cargo.toml | awk 'match($0, /name = \"(.*)\"/, v) {print v[1]}'"] }
PKG_VERSION = { script = ["cat Cargo.toml | awk 'match($0, /version = \"([0-9.].+)\"/, v) {print v[1]}'"] }
PKG_BIN_DIR = "./bin"
PKG_BIN_PATH = "${PKG_BIN_DIR}/${PKG_NAME}"

[tasks.clean_artifacts]
command = "cargo"
args = ["clean"]

[tasks.clean_bin]
script = ["rm -rf bin"]

[tasks.clean]
dependencies = [
	"clean_artifacts",
	"clean_bin"
]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.mkdir]
script = ["mkdir -p ${PKG_BIN_DIR}"]

[tasks.copy]
script = ["cp -rf target/${PKG_PLATFORM}/release/${PKG_NAME} ${PKG_BIN_DIR}"]

[tasks.strip]
script = ["strip ${PKG_BIN_PATH}"]

[tasks.size]
script = ["du -sh ${PKG_BIN_PATH}"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "--target", "${PKG_PLATFORM}"]

[tasks.docker_image]
script = ["docker build -t ${PKG_NAME} -f ./docker/sws.dockerfile ."]

[tasks.release]
dependencies = [
	"clean",
	"build",
	"mkdir",
	"copy",
	"strip",
	"size"
]
