[env]
E_ARGS = ""
E_URL = "https://joseluisq.net"

[tasks.watch]
command = "cargo"
args = ["watch", "-cx", "run -- ${E_ARGS}"]

[tasks.run]
command = "cargo"
args = ["run", "run -- ${E_ARGS}"]

[tasks.loadtest]
script = [
    "echo GET $E_URL | vegeta -cpus=12 attack -workers=10 -duration=60s -connections=10000 -rate=200 -http2=true | tee results.bin | vegeta report",
	"cat results.bin | vegeta report -reporter=plot > plot.html"
]
