version: "3.3"

services:

  service1:
    image: joseluisq/static-web-server:latest
    environment:
      - SERVER_HOST=127.0.0.1
      - SERVER_PORT=8080
      - SERVER_NAME=Server-1
      - SERVICE_NAME=service1

    # configs:
    #   - source: docker_registry_service
    #     target: /etc/envoy-service.yaml
    volumes:
      - ./envoy-service.yaml:/etc/envoy-service.yaml
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    networks:
      envoymesh:
        aliases:
          - service1

#configs:
#  docker_registry_service:
#    external: true

networks:
  envoymesh:
    external:
      name: envoymesh
